### ISSUE TITLE
Net::Dropbear::SSHd fails to install via CPAN on Ubuntu 20.10 (groovy)

### ISSUE THREAD

**Issue by RemenVO** [atrodo/Net-Dropbear#5]
CPAN install of Net::Dropbear::SSHd fails with linker issue:
[...]
/usr/bin/ld: common-channel.o:(.bss+0x0): multiple definition of `hooks'; common-session.o:(.bss+0x0): first defined here
/usr/bin/ld: svr-authpasswd.o:(.bss+0x0): multiple definition of `hooks'; common-session.o:(.bss+0x0): first defined here
/usr/bin/ld: svr-authpubkey.o:(.bss+0x0): multiple definition of `hooks'; common-session.o:(.bss+0x0): first defined here
/usr/bin/ld: svr-session.o:(.bss+0x0): multiple definition of `hooks'; common-session.o:(.bss+0x0): first defined here
/usr/bin/ld: svr-chansession.o:(.bss+0x0): multiple definition of `hooks'; common-session.o:(.bss+0x0): first defined here
/usr/bin/ld: svr-runopts.o:(.bss+0x0): multiple definition of `hooks'; common-session.o:(.bss+0x0): first defined here
/usr/bin/ld: svr-main.o:(.bss+0x0): multiple definition of `hooks'; common-session.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:192: dropbear] Error 1
Unable to build dropbear: Error running cd dropbear/ && make (No such file or directory)

system info:
_uname -a_:
Linux macro 5.8.0-50-generic #56-Ubuntu SMP Mon Apr 12 17:18:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

_lsb_release -a_:
Distributor ID: Ubuntu
Description:    Ubuntu 20.10
Release:        20.10
Codename:       groovy

Install fails on multiple systems (all clean loads of the OS, fully updated.)

**Comment by atrodo** [comment]
I've been able to successfully reproduce the issue, it appears that GCC 10 has made `-fno-common` on by default which does not allow uninitialized global variables. The patch I am applying to dropbear to add hooks was creating one such global variable.

I have been able to fix the issue so that it will compile under `-fno-common` but am having issues upgrading dropbear to the newest version, 2020.81. I plan on getting that straightened out and releasing 0.14 in the next couple days.

**Comment by atrodo** [comment]
I just released 0.14 which will compile cleanly under GCC 10 with `-fno-common`.

**Comment by eserte** [comment]
Unfortunately this linker issue still appears with 0.14. Seen on fedora and debian 11:
```
...
LD_RUN_PATH="/lib/../lib64" cc  -shared -O2 -L/usr/local/lib -fstack-protector-strong  Dropbear.o dropbear/dbutil.o dropbear/buffer.o dropbear/dbhelpers.o dropbear/dss.o dropbear/bignum.o dropbear/signkey.o dropbear/rsa.o dropbear/dbrandom.o dropbear/queue.o dropbear/atomicio.o dropbear/compat.o dropbear/fake-rfc2553.o dropbear/ltc_prng.o dropbear/ecc.o dropbear/ecdsa.o dropbear/crypto_desc.o dropbear/curve25519.o dropbear/ed25519.o dropbear/dbmalloc.o dropbear/gensignkey.o dropbear/gendss.o dropbear/genrsa.o dropbear/gened25519.o dropbear/common-session.o dropbear/packet.o dropbear/common-algo.o dropbear/common-kex.o dropbear/common-channel.o dropbear/common-chansession.o dropbear/termcodes.o dropbear/loginrec.o dropbear/tcp-accept.o dropbear/listener.o dropbear/process-packet.o dropbear/dh_groups.o dropbear/common-runopts.o dropbear/circbuffer.o dropbear/list.o dropbear/netio.o dropbear/chachapoly.o dropbear/gcm.o dropbear/svr-kex.o dropbear/svr-auth.o dropbear/sshpty.o dropbear/svr-authpasswd.o dropbear/svr-authpubkey.o dropbear/svr-authpubkeyoptions.o dropbear/svr-session.o dropbear/svr-service.o dropbear/svr-chansession.o dropbear/svr-runopts.o dropbear/svr-agentfwd.o dropbear/svr-main.o dropbear/svr-x11fwd.o dropbear/svr-tcpfwd.o dropbear/svr-authpam.o dropbear/libtomcrypt/libtomcrypt.a dropbear/libtommath/libtommath.a  -o blib/arch/auto/Net/Dropbear/Dropbear.so  \
   -lutil -lz -lcrypt   \

/usr/bin/ld: dropbear/svr-main.o:(.bss+0x0): multiple definition of `hooks'; Dropbear.o:(.bss+0x20): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:497: blib/arch/auto/Net/Dropbear/Dropbear.so] Error 1
(/usr/bin/make exited with 512)
```

**Comment by XanC** [comment]
I'm having the same problem as eserte, trying to build on Debian 11 Bullseye.

Was able to get around it by manually setting "-fcommon" in the Makefile.

**Comment by atrodo** [comment]
After checking again, I discovered that while I made Dropbear clean in regards to `-fno-common`, I did not make `Dropbear.xs` also. I just released 0.15 in hopes to correct that.
